---
title: "SCOR_data_cleaning"
author: "NN"
date: "2023-01-02"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

#Calling initially relevant libaries
library(tidyverse)
library(summarytools)
library(lubridate)
library(devtools)

#Calling datasets
load("E:\\workdata\\707957\\_DataIn\\R\\Basic\\t_dodsaarsaag_1.rdata")
load("E:\\workdata\\707957\\_DataIn\\R\\Basic\\t_dodsaarsaag_2.rdata")
load("E:\\workdata\\707957\\_DataIn\\R\\Basic\\samlpop_707957.rdata")


#Renaming pnr variables
t_dodsaarsag_1 <- rename(t_dodsaarsag_1, pnr = k_cpr)
t_dodsaarsag_2 <- rename(t_dodsaarsag_2, pnr = k_cpr)
```

## Cleaning cohort 1972-1987
```{r}

load("E:\\workdata\\707957\\_DataIn\\R\\Basic\\t_scor_1972_1987.rdata")

#Renaming pnr variables
t_scor_1972_1987 <- rename(t_scor_1972_1987, pnr = cprnr)

#Merging basic SCOR datasets
scor7287 <- left_join(t_scor_1972_1987, samlpop_707957, by="pnr", all=T) %>%
  distinct() # Removing all duplicates

#Calculating current age
currentdate <- as.Date("2022-01-01")
require(lubridate)
scor7287$currentage <- trunc((scor7287$fodedto%--%currentdate)/years(1))

#Calculating age at death
scor7287 <- left_join(scor7287, t_dodsaarsag_1, by="pnr", all=T) %>% 
  left_join(., t_dodsaarsag_2, by = "pnr", all=T)
require(lubridate)
scor7287$age_at_death <-trunc((scor7287$fodedto %--%scor7287$D_DODSDTO)/years(1))

#Calculating age at examination
scor7287$ageatexam <-trunc((scor7287$fodedto %--%scor7287$statusdato)/years(1))

#Create grouping into valid and invalid entries (dead before 1972, age at examination above 19 (N invalid entries=981)
scor7287$validage[scor7287$ageatexam >= 0] <- "Valid"
scor7287$validage[scor7287$ageatexam >= 19]<- "Invalid"
scor7287$validage[scor7287$age_at_death <= 1] <- "Invalid"
scor7287$validage[scor7287$currentage<34] <- "Invalid"

#Removing invalid entries
scor7287 <- scor7287[(scor7287$validage =="Valid"),]

#Recoding PATOLOGISKE_POCHER for 0/1 instead of NA/X
scor7287$PATOLOGISKE_POCHER[scor7287$PATOLOGISKE_POCHER == "NA"] <- 0
scor7287$PATOLOGISKE_POCHER[scor7287$PATOLOGISKE_POCHER == "X"] <- 1

#Making proxy variables for gingivitis/periodontitis for comparison across cohorts
scor7287$gingivitisindex <- as.numeric(scor7287$gingivitisindex)
scor7287$gingivitis <- ifelse(scor7287$gingivitisindex >= 9, 1, 0)
scor7287$PATOLOGISKE_POCHER <- as.numeric(scor7287$PATOLOGISKE_POCHER)
scor7287$perio <- ifelse(scor7287$PATOLOGISKE_POCHER == 1, 1, 0)

#Making proxy variable for dmf_s, note that code 5 usually included today does not exist for this dataset, and thus cannot be included. In addition code everyone with n_surfaces larger than 148/88 as 0, as it is not possible to have more surfaces than that registered (given incisal edges noted as belonging to another surface when scoring)
scor7287 <- scor7287 %>%  
   group_by(pnr, statusdato) %>%
    dplyr::mutate(dmfs_temp = sum(FLADE_1_1, FLADE_2_1, FLADE_4_1, FLADE_6_1)) %>%
    dplyr::mutate(dmfs_perm = sum(FLADE_1_2, FLADE_2_2, FLADE_4_2, FLADE_6_2)) %>% 
  ungroup


#Detaching datasets no longer needed
remove(t_scor_1972_1987)

```

## Cleaning cohort 1988-1994

```{r}

load("E:\\workdata\\707957\\DataIn\\R\\Basic\\t_scor_1988_1994_vs1.rdata")

#Renaming pnr variables
t_scor_1988_1994 <- rename(t_scor_1988_1994, pnr = cprnr)

#Joining datasets
scor8894 <- left_join(t_scor_1988_1994, samlpop_707957, by="pnr", all=T) %>%
  distinct() # Removing all duplicates, 

#Calculating current age
currentdate <- as.Date("2022-01-01")
require(lubridate)
scor8894$currentage <-trunc((scor8894$fodedto %--%currentdate)/years(1))

#Calculating age at death
scor8894 <- left_join(scor8894, t_dodsaarsag_1, by="pnr", all=T) %>% 
  left_join(., t_dodsaarsag_2, by = "pnr", all=T)
require(lubridate)
scor8894$age_at_death <-trunc((scor8894$fodedto %--%scor8894$D_DODSDTO)/years(1))

#Calculating age at examination
scor8894$ageatexam <-trunc((scor8894$fodedto %--%scor8894$statusdato)/years(1))

#Create grouping into valid and invalid age (N invalid entries=259)
scor8894$validage <- ifelse(scor8894$ageatexam>=0 & scor8894$ageatexam<19,"Valid", "Invalid")

#Removing invalid entries
scor8894 <- scor8894[(scor8894$validage =="Valid"),]

#Making proxy variables for gingivitis/periodontitis for comparison across cohorts
scor8894$gingiv2 <- as.numeric(scor8894$gingiv2)
scor8894$gingivitis <- ifelse(scor8894$gingiv2 > 5, 1, 0)
scor8894$forstet5 <- as.numeric(scor8894$forstet5)
scor8894$perio <- ifelse(scor8894$forstet5 > 0, 1, 0)

#Making proxy variable for dmf_s, note that code 5 usually included today does not exist for this dataset, and thus cannot be included. In addition code everyone with n_surfaces larger than 148/88 as 0, as it is not possible to have more surfaces than that registered (given incisal edges noted as belonging to another surface when scoring)
scor8894 <- scor8894 %>%  
   group_by(pnr, statusdato) %>%
    dplyr::mutate(dmfs_temp = sum(flade_1_1, flade_2_1, flade_4_1, flade_6_1)) %>%
    dplyr::mutate(dmfs_perm = sum(flade_1_2, flade_2_2, flade_4_2, flade_6_2)) %>% 
  ungroup

#Detaching datasets no longer needed
remove(t_scor_1988_1994)
```

##Cleaning cohort t_scor_1995

```{r}
load("E:\\workdata\\707957\\DataIn\\R\\Basic\\t_scor_1995.rdata")


#Renaming pnr variables
t_scor_1995 <- rename(t_scor_1995, pnr = cprnr)


#Merging basic SCOR datasets
scor95<- left_join(t_scor_1995, samlpop_707957, by="pnr", all=T) %>%
  distinct()  # Checking for/removing duplicate

#Removing rows that are just NA (N=3)
scor95 <- scor95[grepl("^NA", rownames(scor95)) ==F,]
scor95 <- scor95[!is.na(scor95$pnr),]

#Calculating current age
currentdate <- as.Date("2022-01-01")
require(lubridate)
scor95$currentage <-trunc((scor95$fodedto %--%currentdate)/years(1))

#Calculating age at death
scor95 <- left_join(scor95, t_dodsaarsag_1, by="pnr", all=T) %>% 
  left_join(., t_dodsaarsag_2, by = "pnr", all=T)
require(lubridate)
scor95$age_at_death <-trunc((scor95$fodedto %--%scor95$D_DODSDTO)/years(1))

#Calculating age at examination
scor95$ageatexam <-trunc((scor95$fodedto %--%scor95$dato)/years(1))

#Create grouping into valid and invalid age + NA pnr(N invalid entries=74)
scor95$validage <- ifelse(scor95$ageatexam>=0 & scor95$ageatexam<19, "Valid", "Invalid")

#Removing invalid entries 
scor95 <- scor95[(scor95$validage =="Valid"),]

#Renaming dato to statusdato
scor95 <- rename(scor95, statusdato = dato)

#Making inderetningsaar proxy variable for chohort 1995-now
scor95$indberetningsaar <- format(as.Date(scor95$statusdato, format="%d/%m/%Y"),"%Y")

#Making aggregate variables for gingivitis/periodontitis for comparison across cohorts

##coding gingivitis proxy
scor95$indberetningsaar <- as.numeric(scor95$indberetningsaar)
scor95$GINGIV1 <- as.numeric(scor95$GINGIV1)
scor95$GINGIV2 <- as.numeric(scor95$GINGIV2)

scor95$gingivitis <- ifelse(scor95$GINGIV2 > 5 & scor95$indberetningsaar < 1999 | scor95$indberetningsaar >= 1999 & scor95$GINGIV1 > 5, 1, 0)

##Coding perio proxy

scor95$POCH11_51[(scor95$POCH11_51 == "X")] <- 0
scor95$POCH12_52[(scor95$POCH12_52 == "X")] <- 0
scor95$POCH16_56[(scor95$POCH16_56 == "X")] <- 0
scor95$POCH21_61[(scor95$POCH21_61 == "X")] <- 0
scor95$POCH22_62[(scor95$POCH22_62 == "X")] <- 0
scor95$POCH26_66[(scor95$POCH26_66 == "X")] <- 0
scor95$POCH31_71[(scor95$POCH31_71 == "X")] <- 0
scor95$POCH32_72[(scor95$POCH32_72 == "X")] <- 0
scor95$POCH36_76[(scor95$POCH36_76 == "X")] <- 0
scor95$POCH41_81[(scor95$POCH41_81 == "X")] <- 0
scor95$POCH42_82[(scor95$POCH42_82 == "X")] <- 0
scor95$POCH46_86[(scor95$POCH46_86 == "X")] <- 0

scor95$FORSTET5 <- as.numeric(scor95$FORSTET5)
scor95$POCH11_51 <- as.numeric(scor95$POCH11_51)
scor95$POCH12_52 <- as.numeric(scor95$POCH12_52)
scor95$POCH16_56 <- as.numeric(scor95$POCH16_56)
scor95$POCH21_61 <- as.numeric(scor95$POCH21_61)
scor95$POCH22_62 <- as.numeric(scor95$POCH22_62)
scor95$POCH26_66 <- as.numeric(scor95$POCH26_66)
scor95$POCH31_71 <- as.numeric(scor95$POCH31_71)
scor95$POCH32_72 <- as.numeric(scor95$POCH32_72)
scor95$POCH36_76 <- as.numeric(scor95$POCH36_76)
scor95$POCH41_81 <- as.numeric(scor95$POCH41_81)
scor95$POCH42_82 <- as.numeric(scor95$POCH42_82)
scor95$POCH46_86 <- as.numeric(scor95$POCH46_86)

scor95 <- scor95 %>% 
  group_by(pnr, statusdato) %>% 
  dplyr::mutate(pato_poch = sum(POCH36_76, POCH32_72, POCH31_71, POCH46_86, POCH42_82, POCH41_81, POCH26_66, POCH22_62, POCH21_61,POCH16_56, POCH12_52, POCH11_51, na.rm=T)) %>% 
  ungroup


scor95$perio <- ifelse(scor95$FORSTET5 >0 & scor95$indberetningsaar < 1999 | scor95$pato_poch > 5 & scor95$indberetningsaar >= 1999, FLADE, 1, 0)

#Making proxy variable for dmf_s, note that code 5 usually included today does not exist for this dataset, and thus cannot be included. In addition code everyone with n_surfaces larger than 148/88 as 0, as it is not possible to have more surfaces than that registered (given incisal edges noted as belonging to another surface when scoring)

scor95$FLADE_1_1 <- as.numeric(scor95$FLADE_1_1)
scor95$FLADE_2_1 <- as.numeric(scor95$FLADE_2_1)
scor95$FLADE_4_1 <- as.numeric(scor95$FLADE_4_1) 
scor95$FLADE_6_1 <- as.numeric(scor95$FLADE_6_1)
scor95$FLADE_1_2 <- as.numeric(scor95$FLADE_1_2)
scor95$FLADE_2_2 <- as.numeric(scor95$FLADE_2_2)
scor95$FLADE_4_2 <- as.numeric(scor95$FLADE_4_2) 
scor95$FLADE_6_2 <- as.numeric(scor95$FLADE_6_2) 


scor95 <- scor95 %>%  
   group_by(pnr, statusdato) %>%
    dplyr::mutate(dmfs_temp = sum(FLADE_1_1, FLADE_2_1, FLADE_4_1, FLADE_6_1)) %>%
    dplyr::mutate(dmfs_perm = sum(FLADE_1_2, FLADE_2_2, FLADE_4_2, FLADE_6_2)) %>% 
  ungroup


#Detaching datasets no longer needed
remove(t_scor_1995, samlpop_707957, t_dodsaarsag_1, t_dodsaarsag_2)
```

## Merging the three cohorts into one dataset, adding additional variables

```{r}

#Gathering the three cohorts into SCOR:
scor <-plyr::rbind.fill(scor7287, scor8894, scor95)

#Coding sorting variable based on dataset
scor$dataset[scor$indberetningsaar>= 1973 & scor$indberetningsaar<=1987] <- "1972-1987"
scor$dataset[scor$indberetningsaar>= 1988 & scor$indberetningsaar<=1994] <- "1988-1994"
scor$dataset[scor$indberetningsaar>= 1995] <- "1995-current"


#Creating variable for year of birth and year of visit
scor$visit_year <- format(as.Date(scor$statusdato, format="%d/%m/%Y"),"%Y")
scor$birth_year <- format(as.Date(scor$fodedto, format="%d/%m/%Y"),"%Y")

#Cleaning dmf_s variables of illogical values
scor95$dmfs_temp[scor95$dmfs_temp > 88] <- 0
scor95$dmfs_perm[scor95$dmfs_perm > 148] <- 0

#creating dmfs variable as sum of temp and perm teeth dmfs.
scor <- scor %>% 
  group_by(pnr, statusdato) %>% 
  mutate(., dmfs = sum(dmfs_temp, dmfs_perm))

#Saving dataset
save(scor, file="E:\\workdata\\707957\\ID-NN\\Results\\scor.rdata")

#Detaching datasets
rm(scor7287, scor8894, scor95)
```
